# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solutionSudoku.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QValidator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 630)
        MainWindow.setMinimumSize(QtCore.QSize(830, 630))  # 设置窗口为固定大小
        MainWindow.setMaximumSize(QtCore.QSize(830, 630))  # 设置窗口为固定大小
        MainWindow.setDocumentMode(False)
        MainWindow.setStyleSheet("#MainWindow{background-color: gray}")
        # MainWindow.setStyleSheet("#MainWindow{border-image:url(./images/python.jpg);}")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 150, 401, 431))
        self.widget.setObjectName("widget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        fontNum = QtGui.QFont()
        fontNum.setFamily("微软雅黑")
        fontNum.setBold(True)
        fontNum.setPointSize(10)
        fontNum.setWeight(40)

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_1.setFont(fontNum)
        self.lineEdit_1.setText("0")
        # self.lineEdit_1.setPlaceholderText('0')       # 默认提示文字
        self.lineEdit_1.setCursorPosition(0)
        self.lineEdit_1.setMaxLength(1)                 # 设置允许输入字符的最大长度

        self.lineEdit_1.setFocus()
        self.lineEdit_1.selectAll()
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setClearButtonEnabled(False)

        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 0, 0, 1, 1)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setFont(fontNum)
        self.lineEdit_2.setText("0")
        self.lineEdit_2.setMaxLength(1)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setFont(fontNum)
        self.lineEdit_3.setText("0")
        self.lineEdit_3.setMaxLength(1)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setFont(fontNum)
        self.lineEdit_4.setText("0")
        self.lineEdit_4.setMaxLength(1)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 3, 1, 1)

        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setFont(fontNum)
        self.lineEdit_5.setText("0")
        self.lineEdit_5.setMaxLength(1)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 4, 1, 1)

        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setFont(fontNum)
        self.lineEdit_6.setText("0")
        self.lineEdit_6.setMaxLength(1)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 0, 5, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setFont(fontNum)
        self.lineEdit_7.setText("0")
        self.lineEdit_7.setMaxLength(1)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 6, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setFont(fontNum)
        self.lineEdit_8.setText("0")
        self.lineEdit_8.setMaxLength(1)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 0, 7, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setFont(fontNum)
        self.lineEdit_9.setText("0")
        self.lineEdit_9.setMaxLength(1)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 0, 8, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setFont(fontNum)
        self.lineEdit_10.setText("0")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setFont(fontNum)
        self.lineEdit_11.setText("0")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setText("0")
        self.lineEdit_12.setFont(fontNum)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 1, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setFont(fontNum)
        self.lineEdit_13.setText("0")
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 1, 3, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setFont(fontNum)
        self.lineEdit_14.setText("0")
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 1, 4, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setFont(fontNum)
        self.lineEdit_15.setText("0")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 1, 5, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_16.setFont(fontNum)
        self.lineEdit_16.setText("0")
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 1, 6, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_17.setFont(fontNum)
        self.lineEdit_17.setText("0")
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 1, 7, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_18.setFont(fontNum)
        self.lineEdit_18.setText("0")
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 1, 8, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_19.setFont(fontNum)
        self.lineEdit_19.setText("0")
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 2, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setFont(fontNum)
        self.lineEdit_20.setText("0")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout.addWidget(self.lineEdit_20, 2, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_21.setFont(fontNum)
        self.lineEdit_21.setText("0")
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout.addWidget(self.lineEdit_21, 2, 2, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_22.setFont(fontNum)
        self.lineEdit_22.setText("0")
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout.addWidget(self.lineEdit_22, 2, 3, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_23.setFont(fontNum)
        self.lineEdit_23.setText("0")
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout.addWidget(self.lineEdit_23, 2, 4, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24.setFont(fontNum)
        self.lineEdit_24.setText("0")
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout.addWidget(self.lineEdit_24, 2, 5, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_25.setFont(fontNum)
        self.lineEdit_25.setText("0")
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout.addWidget(self.lineEdit_25, 2, 6, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_26.setFont(fontNum)
        self.lineEdit_26.setText("0")
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout.addWidget(self.lineEdit_26, 2, 7, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_27.setFont(fontNum)
        self.lineEdit_27.setText("0")
        self.lineEdit_27.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout.addWidget(self.lineEdit_27, 2, 8, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_28.setText("0")
        self.lineEdit_28.setFont(fontNum)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout.addWidget(self.lineEdit_28, 3, 0, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_29.setFont(fontNum)
        self.lineEdit_29.setText("0")
        self.lineEdit_29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout.addWidget(self.lineEdit_29, 3, 1, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_30.setFont(fontNum)
        self.lineEdit_30.setText("0")
        self.lineEdit_30.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout.addWidget(self.lineEdit_30, 3, 2, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_31.setFont(fontNum)
        self.lineEdit_31.setText("0")
        self.lineEdit_31.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout.addWidget(self.lineEdit_31, 3, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_32.setFont(fontNum)
        self.lineEdit_32.setText("0")
        self.lineEdit_32.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout.addWidget(self.lineEdit_32, 3, 4, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_33.setFont(fontNum)
        self.lineEdit_33.setText("0")
        self.lineEdit_33.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout.addWidget(self.lineEdit_33, 3, 5, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_34.setFont(fontNum)
        self.lineEdit_34.setText("0")
        self.lineEdit_34.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout.addWidget(self.lineEdit_34, 3, 6, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_35.setFont(fontNum)
        self.lineEdit_35.setText("0")
        self.lineEdit_35.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout.addWidget(self.lineEdit_35, 3, 7, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_36.setFont(fontNum)
        self.lineEdit_36.setText("0")
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout.addWidget(self.lineEdit_36, 3, 8, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_37.setFont(fontNum)
        self.lineEdit_37.setText("0")
        self.lineEdit_37.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout.addWidget(self.lineEdit_37, 4, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_38.setFont(fontNum)
        self.lineEdit_38.setText("0")
        self.lineEdit_38.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout.addWidget(self.lineEdit_38, 4, 1, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_39.setFont(fontNum)
        self.lineEdit_39.setText("0")
        self.lineEdit_39.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout.addWidget(self.lineEdit_39, 4, 2, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_40.setFont(fontNum)
        self.lineEdit_40.setText("0")
        self.lineEdit_40.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout.addWidget(self.lineEdit_40, 4, 3, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_41.setFont(fontNum)
        self.lineEdit_41.setText("0")
        self.lineEdit_41.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout.addWidget(self.lineEdit_41, 4, 4, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_42.setFont(fontNum)
        self.lineEdit_42.setText("0")
        self.lineEdit_42.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout.addWidget(self.lineEdit_42, 4, 5, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_43.setFont(fontNum)
        self.lineEdit_43.setText("0")
        self.lineEdit_43.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout.addWidget(self.lineEdit_43, 4, 6, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_44.setFont(fontNum)
        self.lineEdit_44.setText("0")
        self.lineEdit_44.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout.addWidget(self.lineEdit_44, 4, 7, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_45.setFont(fontNum)
        self.lineEdit_45.setText("0")
        self.lineEdit_45.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout.addWidget(self.lineEdit_45, 4, 8, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_46.setFont(fontNum)
        self.lineEdit_46.setText("0")
        self.lineEdit_46.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout.addWidget(self.lineEdit_46, 5, 0, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_47.setFont(fontNum)
        self.lineEdit_47.setText("0")
        self.lineEdit_47.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout.addWidget(self.lineEdit_47, 5, 1, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_48.setFont(fontNum)
        self.lineEdit_48.setText("0")
        self.lineEdit_48.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout.addWidget(self.lineEdit_48, 5, 2, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_49.setFont(fontNum)
        self.lineEdit_49.setText("0")
        self.lineEdit_49.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout.addWidget(self.lineEdit_49, 5, 3, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_50.setFont(fontNum)
        self.lineEdit_50.setText("0")
        self.lineEdit_50.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout.addWidget(self.lineEdit_50, 5, 4, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_51.setFont(fontNum)
        self.lineEdit_51.setText("0")
        self.lineEdit_51.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout.addWidget(self.lineEdit_51, 5, 5, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_52.setFont(fontNum)
        self.lineEdit_52.setText("0")
        self.lineEdit_52.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout.addWidget(self.lineEdit_52, 5, 6, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_53.setFont(fontNum)
        self.lineEdit_53.setText("0")
        self.lineEdit_53.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout.addWidget(self.lineEdit_53, 5, 7, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_54.setFont(fontNum)
        self.lineEdit_54.setText("0")
        self.lineEdit_54.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout.addWidget(self.lineEdit_54, 5, 8, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_55.setFont(fontNum)
        self.lineEdit_55.setText("0")
        self.lineEdit_55.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout.addWidget(self.lineEdit_55, 6, 0, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_56.setFont(fontNum)
        self.lineEdit_56.setText("0")
        self.lineEdit_56.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout.addWidget(self.lineEdit_56, 6, 1, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_57.setFont(fontNum)
        self.lineEdit_57.setText("0")
        self.lineEdit_57.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout.addWidget(self.lineEdit_57, 6, 2, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_58.setFont(fontNum)
        self.lineEdit_58.setText("0")
        self.lineEdit_58.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout.addWidget(self.lineEdit_58, 6, 3, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_59.setFont(fontNum)
        self.lineEdit_59.setText("0")
        self.lineEdit_59.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout.addWidget(self.lineEdit_59, 6, 4, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_60.setFont(fontNum)
        self.lineEdit_60.setText("0")
        self.lineEdit_60.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout.addWidget(self.lineEdit_60, 6, 5, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_61.setFont(fontNum)
        self.lineEdit_61.setText("0")
        self.lineEdit_61.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout.addWidget(self.lineEdit_61, 6, 6, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_62.setFont(fontNum)
        self.lineEdit_62.setText("0")
        self.lineEdit_62.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout.addWidget(self.lineEdit_62, 6, 7, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_63.setFont(fontNum)
        self.lineEdit_63.setText("0")
        self.lineEdit_63.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout.addWidget(self.lineEdit_63, 6, 8, 1, 1)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_64.setFont(fontNum)
        self.lineEdit_64.setText("0")
        self.lineEdit_64.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout.addWidget(self.lineEdit_64, 7, 0, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_65.setFont(fontNum)
        self.lineEdit_65.setText("0")
        self.lineEdit_65.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout.addWidget(self.lineEdit_65, 7, 1, 1, 1)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_66.setFont(fontNum)
        self.lineEdit_66.setText("0")
        self.lineEdit_66.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout.addWidget(self.lineEdit_66, 7, 2, 1, 1)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_67.setFont(fontNum)
        self.lineEdit_67.setText("0")
        self.lineEdit_67.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.gridLayout.addWidget(self.lineEdit_67, 7, 3, 1, 1)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_68.setFont(fontNum)
        self.lineEdit_68.setText("0")
        self.lineEdit_68.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.gridLayout.addWidget(self.lineEdit_68, 7, 4, 1, 1)
        self.lineEdit_69 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_69.setFont(fontNum)
        self.lineEdit_69.setText("0")
        self.lineEdit_69.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.gridLayout.addWidget(self.lineEdit_69, 7, 5, 1, 1)
        self.lineEdit_70 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_70.setFont(fontNum)
        self.lineEdit_70.setText("0")
        self.lineEdit_70.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.gridLayout.addWidget(self.lineEdit_70, 7, 6, 1, 1)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_71.setFont(fontNum)
        self.lineEdit_71.setText("0")
        self.lineEdit_71.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.gridLayout.addWidget(self.lineEdit_71, 7, 7, 1, 1)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_72.setFont(fontNum)
        self.lineEdit_72.setText("0")
        self.lineEdit_72.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.gridLayout.addWidget(self.lineEdit_72, 7, 8, 1, 1)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_73.setFont(fontNum)
        self.lineEdit_73.setText("0")
        self.lineEdit_73.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.gridLayout.addWidget(self.lineEdit_73, 8, 0, 1, 1)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_74.setFont(fontNum)
        self.lineEdit_74.setText("0")
        self.lineEdit_74.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.gridLayout.addWidget(self.lineEdit_74, 8, 1, 1, 1)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_75.setFont(fontNum)
        self.lineEdit_75.setText("0")
        self.lineEdit_75.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.gridLayout.addWidget(self.lineEdit_75, 8, 2, 1, 1)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_76.setFont(fontNum)
        self.lineEdit_76.setText("0")
        self.lineEdit_76.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.gridLayout.addWidget(self.lineEdit_76, 8, 3, 1, 1)
        self.lineEdit_77 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_77.setFont(fontNum)
        self.lineEdit_77.setText("0")
        self.lineEdit_77.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.gridLayout.addWidget(self.lineEdit_77, 8, 4, 1, 1)
        self.lineEdit_78 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_78.setFont(fontNum)
        self.lineEdit_78.setText("0")
        self.lineEdit_78.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.gridLayout.addWidget(self.lineEdit_78, 8, 5, 1, 1)
        self.lineEdit_79 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_79.setFont(fontNum)
        self.lineEdit_79.setText("0")
        self.lineEdit_79.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.gridLayout.addWidget(self.lineEdit_79, 8, 6, 1, 1)

        self.lineEdit_80 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_80.setFont(fontNum)
        self.lineEdit_80.setText("0")
        self.lineEdit_80.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.gridLayout.addWidget(self.lineEdit_80, 8, 7, 1, 1)

        self.lineEdit_81 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_81.setFont(fontNum)
        self.lineEdit_81.setText("0")
        self.lineEdit_81.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.gridLayout.addWidget(self.lineEdit_81, 8, 8, 1, 1)

        self.horizontalLayout.addLayout(self.gridLayout)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(630, 230, 95, 241))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.pushButton.clicked.connect(self.result)  # 单击解出数独
        self.pushButton_2.clicked.connect(self.reset)  # 单击重置数独


        self.lineEdit_1.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.lineEdit_15.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_19.raise_()
        self.lineEdit_20.raise_()
        self.lineEdit_21.raise_()
        self.lineEdit_22.raise_()
        self.lineEdit_23.raise_()
        self.lineEdit_24.raise_()
        self.lineEdit_25.raise_()
        self.lineEdit_26.raise_()
        self.lineEdit_27.raise_()
        self.lineEdit_28.raise_()
        self.lineEdit_29.raise_()
        self.lineEdit_30.raise_()
        self.lineEdit_31.raise_()
        self.lineEdit_32.raise_()
        self.lineEdit_33.raise_()
        self.lineEdit_34.raise_()
        self.lineEdit_30.raise_()
        self.lineEdit_31.raise_()
        self.lineEdit_32.raise_()
        self.lineEdit_33.raise_()
        self.lineEdit_34.raise_()
        self.lineEdit_35.raise_()
        self.lineEdit_36.raise_()
        self.lineEdit_42.raise_()
        self.lineEdit_43.raise_()
        self.lineEdit_44.raise_()
        self.lineEdit_45.raise_()
        self.lineEdit_46.raise_()
        self.lineEdit_47.raise_()
        self.lineEdit_48.raise_()
        self.lineEdit_49.raise_()
        self.lineEdit_50.raise_()
        self.lineEdit_51.raise_()
        self.lineEdit_52.raise_()
        self.lineEdit_53.raise_()
        self.lineEdit_54.raise_()
        self.lineEdit_55.raise_()
        self.lineEdit_56.raise_()
        self.lineEdit_57.raise_()
        self.lineEdit_58.raise_()
        self.lineEdit_59.raise_()
        self.lineEdit_60.raise_()
        self.lineEdit_61.raise_()
        self.lineEdit_62.raise_()
        self.lineEdit_63.raise_()
        self.lineEdit_64.raise_()
        self.lineEdit_65.raise_()
        self.lineEdit_66.raise_()
        self.lineEdit_67.raise_()
        self.lineEdit_68.raise_()
        self.lineEdit_69.raise_()
        self.lineEdit_70.raise_()
        self.lineEdit_71.raise_()
        self.lineEdit_72.raise_()
        self.lineEdit_73.raise_()
        self.lineEdit_74.raise_()
        self.lineEdit_75.raise_()
        self.lineEdit_76.raise_()
        self.lineEdit_77.raise_()
        self.lineEdit_78.raise_()
        self.lineEdit_79.raise_()
        self.lineEdit_80.raise_()

        self.lineEdit_81.raise_()

        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton.raise_()

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "解数独"))

        # self.lineEdit_1.setPlaceholderText(_translate("MainWindow", "1~9"))

        # self.lineEdit_2.setText(_translate("MainWindow", "0"))

        self.pushButton.setText(_translate("MainWindow", "解出数独"))
        self.pushButton_2.setText(_translate("MainWindow", "重置数独"))

    def beforeFont(self):
        font = QtGui.QFont()
        font.setFamily('微软雅黑')
        font.setBold(True)
        font.setPointSize(10)
        font.setWeight(75)
        return font
